### ISSUE TITLE
Some issues with ObjectId/references

### ISSUE THREAD

**Issue by tryy3** [ddsol/redux-schema#5]
Hello, I must say you have done a good job with this library, the documentation is a bit bad but I have figured out most of the stuff on my own.

But I currently have an issue.
I have 3 models, Command, GroupCommand and Groups.

Command is just a simple Model:
```JavaScript
const Command = {
    command_id: Number,
    command: String,
    name: String,
    description: String,
    format: String
}
```

The problem is that I want GroupCommand to "extend"/reference the Command.
So the setup I have is that Command contains the basic structure of all commands then I can add Command to specific groups/users and it will become a GroupCommand because a GroupCommand has a few more settings.

So right now I have this:
```JavaScript
const GroupCommand = {
    id: ObjectId,
    group_command_id: Number,
    command: reference,
    command_id: Number,
    group_name: String,
    group: reference,
    next_check: Number,
    stop_error: Boolean
};
```

The issue is that if I put the "command" and "group" to ObjectId, the "idkey" parameter for GroupCommand will be set to "group" meaning GroupCommands wont autogenerate a ID.

The problem with reference is that I don't know how to use it...
It doesn't seem to generate any get/setters, instead it becomes a function, so to set a reference I have to do:
```JavaScript
let cmd = store.groupCommands.create(group)
cmd.command(target)
```
But with that I am not able to actually retrieve the target afterwards.

So I am in a bit of a problem here, I am not sure if I am missunderstanding the use of reference/ObjectId but as there isn't much documentations I just assume based on the example in README and the examples in the code.
I guess I could use String to store the ID...

**Comment by ddsol** [comment]
I agree the documentation is downright bad. I haven't had much time to work on it.

A reference to another model is created like this:

```js
import schemaStore, { model, optional, reference, collections, owner, scratch } from 'redux-schema';
import { createStore } from 'redux';

const commandModel = model('Command', {
  command: String,
  name: String,
  description: String,
  format: String,
  get groupCommands() {
    //Back references currently only manual. Not too much code however...
    return owner(owner(this)).groupCommand.all.filter(groupCommand => groupCommand.command === this);
  }
});

const groupModel = model('Group', {
  name: String,
  description: String,
  get groupCommands() {
    return owner(owner(this)).groupCommand.all.filter(groupCommand => groupCommand.group === this);
  }
});

const groupCommandModel = model('GroupCommand', {
  command: reference('command'),
  get groupName() {
    return this.group ? this.group.name : '';
  },
  group: optional(reference('group')),
  nextCheck: Number,
  stopError: Boolean
});

const root = collections([commandModel, groupModel, groupCommandModel]);

const store = schemaStore(root)(createStore)();

const { Command, Group, GroupCommand } = store.models;

const command = new Command({
  command: 'bark',
  name: 'Barking',
  description: 'Woof! Woof!'
});

const group = new Group({
  name: 'Items',
  description: 'A large group of items'
});

const groupCommand = new GroupCommand({
  command,
  group
});

console.log(groupCommand.command.description);
console.log(groupCommand.group.name);
console.log(group.groupCommands[0].nextCheck);
console.log(command.groupCommands[0].nextCheck);

groupCommand.group = undefined; // <- works fine

groupCommand.command = undefined; // <- error (not optional)
```
